dynaconf_merge = true
# Example secrets configuration file, rename as .secrets.toml
[MQTT]
    [MQTT.credentials]
    username = 'user'
    password = 'pass'

[DC09]
    [DC09.encryption]
    enable = false #True/False
    key = "this is a very secret password verysecret" #Min lenght 32 NOT IMPLEMENTED

