#CONFIGURATION FILE FOR SERVER-DATA-FORWARDER
dynaconf_merge = true
[DEFAULT]
#---------MQTT Configuration ---------
[MQTT]
    [MQTT.endpoint]
    #Ip/puerto broker
    address = "192.168.1.99"
    port = 1883

    [MQTT.attributes]
    qos = 0
    #Mqtt application topic
    topic = "application/3/#"
    # True -  JSON marshaler
    # False - Protobuf marshaler (binary)
    marshaler = true    

#---------CID CONFIGURATION ----------    
[CID]
    [CID.attributes]
    enablecheksumvalidation = true
    enablecheksumgenerator = true
    separator = "aa"

#---------SIA DC09 CONFIGURATION-------
[DC09]
    [DC09.endpoint]
    #Ip/puerto recibidora destino
    address = "172.31.224.218" 
    port = 61200
    type = "UDP" # UDP o TCP
    mb = "main" #main/back-up
    ps = "primary"    #primary/secondary

    [DC09.attributes]
    account = "FAFA"
    line = 1
    receiver = 1
    heartbeat = 600 #Intervalo en segundos del keepalive
    pollmsg = "RP"  #Mensaje usado para keepalive CODIGO SIA!
#---------------------------------------